swagger: "3.0"
info:
  description: "API definition is the gold standard. For each implemented rule there are rule violations."
  version: "0.0.1"
  title: "Gold Standard REST-API Rules"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
tags:
- name: "URI Rules"
- name: "Meta Rules"
- name: "Representational Rules"
- name: "HTTP Rules"
- name: "Client Rules"
schemes:
- "https"
paths:
  # Define all paths here          
components:
  # Define all components here
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"