swagger: "3.0"
info:
  description: "API definition is the gold standard. For each implemented rule there are rule violations."
  version: "0.0.1"
  title: "Gold Standard REST-API Rules"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
tags:
- name: "URI Rules"
- name: "Meta Rules"
- name: "Representational Rules"
- name: "HTTP Rules"
- name: "Client Rules"
schemes:
- "https"
paths:
  # Define all paths here          
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
  # RULE 19: using other characters instead of forward slash '/'
  .users.{userId}.permissions:
    get:
      summary: Returns a user permission for ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The perimssion of the user to return.
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: A users permissions.
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  \users\{userId}\permissions:
    get:
      summary: Returns a user permission for ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The perimssion of the user to return.
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: A users permissions.
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
  -users-{userId}-permissions:
    get:
      summary: Returns a user permission for ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The perimssion of the user to return.
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: A users permissions.
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
  \#users\#{userId}\#permissions:
    get:
      summary: Returns a user permission for ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The perimssion of the user to return.
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: A users permissions.
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
  
components:
  # Define all components here
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"